### ISSUE TITLE
я не могу кикнуть себя с сервера

### ISSUE THREAD

**Issue by Lucifer2033** [U61vashka/MC-Auth-with-Link#9]
я через вк нажал кикнуть но он не выполнил 
[08:34:45 ERROR]:       at me.mastercapexd.auth.messenger.commands.KickCommand.onKick(KickCommand.java:16)
[08:34:45 ERROR]:       at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
[08:34:45 ERROR]:       at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:757)
[08:34:45 ERROR]:       at revxrsal.commands.core.reflect.MethodHandlesCallerFactory$1.call(MethodHandlesCallerFactory.java:35)
[08:34:45 ERROR]:       at revxrsal.commands.core.reflect.MethodCaller.lambda$bindTo$0(MethodCaller.java:29)
[08:34:45 ERROR]:       at revxrsal.commands.core.BaseCommandDispatcher.execute(BaseCommandDispatcher.java:88)
[08:34:45 ERROR]:       at revxrsal.commands.core.BaseCommandDispatcher.searchCategory(BaseCommandDispatcher.java:69)
[08:34:45 ERROR]:       at revxrsal.commands.core.BaseCommandDispatcher.eval(BaseCommandDispatcher.java:44)
[08:34:45 ERROR]:       at revxrsal.commands.core.BaseCommandHandler.dispatch(BaseCommandHandler.java:519)
[08:34:45 ERROR]:       at me.mastercapexd.auth.vk.commands.DispatchCommandListener.handleCommandDispatch(DispatchCommandListener.java:62)
[08:34:45 ERROR]:       at me.mastercapexd.auth.vk.commands.DispatchCommandListener.lambda$onButtonClick$4(DispatchCommandListener.java:48)
[08:34:45 ERROR]:       at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[08:34:45 ERROR]:       at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
[08:34:45 ERROR]:       at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
[08:34:45 ERROR]:       at me.mastercapexd.auth.vk.commands.DispatchCommandListener.lambda$onButtonClick$5(DispatchCommandListener.java:46)
[08:34:45 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[08:34:45 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[08:34:45 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Lucifer2033** [comment]
ошибка моя надо после обновления плагина удалить старый кфг
